# Generated by Django 5.1 on 2024-09-06 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Predictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('hypertension', models.BooleanField()),
                ('heart_disease', models.BooleanField()),
                ('smoking_history', models.CharField(max_length=50)),
                ('bmi', models.FloatField()),
                ('HbA1c_level', models.FloatField()),
                ('blood_glucose_level', models.FloatField()),
                ('prediction_result', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
