# Generated by Django 5.1 on 2024-08-29 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='web_users',
        ),
    ]
