# Generated by Django 4.2.15 on 2024-10-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
