# Generated by Django 4.2.15 on 2024-10-07 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
