# Generated by Django 4.2.15 on 2024-10-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_alter_newslettersubscriber_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feed',
            new_name='feedback',
        ),
    ]
