# Generated by Django 5.1 on 2024-09-08 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Glucose_Record', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Records',
        ),
    ]
