# Generated by Django 5.1 on 2024-09-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Glucose_Record', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grecords',
            name='evening',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grecords',
            name='mor_after',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grecords',
            name='mor_fast',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grecords',
            name='night_after',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grecords',
            name='night_fast',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
