# Generated by Django 4.2.15 on 2024-10-07 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MealPlan',
        ),
    ]
